/*
 * Automatically generated by make u-boot: don't edit.
 */
#define CONFIG_FLASH_BOOT_START 0xe2200000
#define CONFIG_FLASH_BOOT_SIZE 0x00040000
#define CONFIG_FLASH_IMAGE_START 0xe2280000
#define CONFIG_FLASH_IMAGE_SIZE 0x00a00000
