
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 8.1.02 EDK_I.20.4
* DO NOT EDIT.
*
*     Author: Xilinx, Inc.
*     
*     
*     This program is free software; you can redistribute it and/or modify it
*     under the terms of the GNU General Public License as published by the
*     Free Software Foundation; either version 2 of the License, or (at your
*     option) any later version.
*     
*     
*     XILINX IS PROVIDING THIS DESIGN, CODE, OR INFORMATION "AS IS" AS A
*     COURTESY TO YOU. BY PROVIDING THIS DESIGN, CODE, OR INFORMATION AS
*     ONE POSSIBLE IMPLEMENTATION OF THIS FEATURE, APPLICATION OR STANDARD,
*     XILINX IS MAKING NO REPRESENTATION THAT THIS IMPLEMENTATION IS FREE
*     FROM ANY CLAIMS OF INFRINGEMENT, AND YOU ARE RESPONSIBLE FOR OBTAINING
*     ANY THIRD PARTY RIGHTS YOU MAY REQUIRE FOR YOUR IMPLEMENTATION.
*     XILINX EXPRESSLY DISCLAIMS ANY WARRANTY WHATSOEVER WITH RESPECT TO
*     THE ADEQUACY OF THE IMPLEMENTATION, INCLUDING BUT NOT LIMITED TO ANY
*     WARRANTIES OR REPRESENTATIONS THAT THIS IMPLEMENTATION IS FREE FROM
*     CLAIMS OF INFRINGEMENT, IMPLIED WARRANTIES OF MERCHANTABILITY AND
*     FITNESS FOR A PARTICULAR PURPOSE.
*     
*     
*     Xilinx hardware products are not intended for use in life support
*     appliances, devices, or systems. Use in such applications is
*     expressly prohibited.
*     
*     
*     (c) Copyright 2002-2005 Xilinx Inc.
*     All rights reserved.
*     
*     
*     You should have received a copy of the GNU General Public License along
*     with this program; if not, write to the Free Software Foundation, Inc.,
*     675 Mass Ave, Cambridge, MA 02139, USA.
* 
* Description: Driver parameters
*
*******************************************************************/

#define XPAR_PLB_V46_PPC405_0_BASEADDR 0x00000108
#define XPAR_PLB_V46_PPC405_0_HIGHADDR 0x0000010F
#define XPAR_PLB_V46_0_BASEADDR 0x00000100
#define XPAR_PLB_V46_0_HIGHADDR 0x00000107
#define XPAR_VGA_DCR_BASEADDR 0x00000110
#define XPAR_VGA_DCR_HIGHADDR 0x00000111

/******************************************************************/

#define XPAR_PLB_BRAM_IF_CNTLR_0_BASEADDR 0xFFFF0000
#define XPAR_PLB_BRAM_IF_CNTLR_0_HIGHADDR 0xFFFFFFFF
/* Definitions for peripheral PLB_BRAM_IF_CNTLR_1 */
#define XPAR_PLB_BRAM_IF_CNTLR_1_BASEADDR 0xEEE00000
#define XPAR_PLB_BRAM_IF_CNTLR_1_HIGHADDR 0xEEE01FFF


/******************************************************************/

#define XPAR_XDDR_NUM_INSTANCES 1
#define XPAR_DDR_SDRAM_32MX64_ECC_BASEADDR 0xFFFFFFFF
#define XPAR_DDR_SDRAM_32MX64_ECC_HIGHADDR 0x00000000
#define XPAR_DDR_SDRAM_32MX64_DEVICE_ID 0
#define XPAR_DDR_SDRAM_32MX64_INCLUDE_ECC_INTR 0

/******************************************************************/

#define XPAR_DDR_SDRAM_32MX64_MEM0_BASEADDR 0x00000000
#define XPAR_DDR_SDRAM_32MX64_MEM0_HIGHADDR 0x1FFFFFFF

/******************************************************************/

#define XPAR_XUARTNS550_NUM_INSTANCES 1
#define XPAR_XUARTNS550_CLOCK_HZ 20000000
#define XPAR_RS232_UART_0_BASEADDR 0xD0000000
#define XPAR_RS232_UART_0_HIGHADDR 0xD0001FFF
#define XPAR_RS232_UART_0_DEVICE_ID 0

/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 1

/* Definitions for peripheral LEDS_8BIT */
#define XPAR_LEDS_8BIT_BASEADDR 0xD0010200
#define XPAR_LEDS_8BIT_HIGHADDR 0xD00103FF
#define XPAR_LEDS_8BIT_DEVICE_ID 0
#define XPAR_LEDS_8BIT_INTERRUPT_PRESENT 1
#define XPAR_LEDS_8BIT_IS_DUAL 0

/******************************************************************/

/* Definitions for driver TFT_REF */
#define XPAR_XTFT_NUM_INSTANCES 1

/* Definitions for peripheral PLB_TFT_CNTLR_REF_0 */
#define XPAR_PLB_TFT_CNTLR_REF_0_DCR_BASEADDR 0x00000110
#define XPAR_PLB_TFT_CNTLR_REF_0_DCR_HIGHADDR 0x00000113
#define XPAR_PLB_TFT_CNTLR_REF_0_DEVICE_ID 0


/******************************************************************/

/* Definitions for driver LLTEMAC */
#define XPAR_XLLTEMAC_NUM_INSTANCES 1

/* Definitions for peripheral LL_TEMAC_0 Channel 0 */
#define XPAR_LL_TEMAC_0_CHAN_0_DEVICE_ID 0
#define XPAR_LL_TEMAC_0_CHAN_0_BASEADDR 0x91200000
#define XPAR_LL_TEMAC_0_CHAN_0_TXCSUM 0
#define XPAR_LL_TEMAC_0_CHAN_0_RXCSUM 0
#define XPAR_LL_TEMAC_0_CHAN_0_PHY_TYPE 0

/* Canonical definitions for peripheral LL_TEMAC_0 Channel 0 */
#define XPAR_XLLTEMAC_0_DEVICE_ID 0
#define XPAR_XLLTEMAC_0_BASEADDR 0x91200000
#define XPAR_XLLTEMAC_0_TXCSUM 0
#define XPAR_XLLTEMAC_0_RXCSUM 0
#define XPAR_XLLTEMAC_0_PHY_TYPE 0
#define XPAR_XLLTEMAC_0_INTR 4


/* LocalLink TYPE Enumerations */
#define XPAR_LL_FIFO    1
#define XPAR_LL_DMA     2


/* Canonical LocalLink parameters for LL_TEMAC_0 */
#define XPAR_XLLTEMAC_0_LLINK_CONNECTED_TYPE XPAR_LL_DMA
#define XPAR_XLLTEMAC_0_LLINK_CONNECTED_BASEADDR 0x80
#define XPAR_XLLTEMAC_0_LLINK_CONNECTED_DMATX_INTR 6
#define XPAR_XLLTEMAC_0_LLINK_CONNECTED_DMARX_INTR 5

/******************************************************************/

/* Definitions for driver IIC */
#define XPAR_XIIC_NUM_INSTANCES 1

/* Definitions for peripheral IIC_BUS */
#define XPAR_IIC_BUS_BASEADDR 0xD0020000
#define XPAR_IIC_BUS_HIGHADDR 0xD00201FF
#define XPAR_IIC_BUS_DEVICE_ID 0
#define XPAR_IIC_BUS_TEN_BIT_ADR 0
#define XPAR_IIC_BUS_GPO_WIDTH 1

/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 7
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_USE_DCR 0
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral OPB_INTC_0 */
#define XPAR_OPB_INTC_0_BASEADDR 0xD0020200
#define XPAR_OPB_INTC_0_HIGHADDR 0xD002021F
#define XPAR_OPB_INTC_0_DEVICE_ID 0
#define XPAR_OPB_INTC_0_KIND_OF_INTR 0x00000000

/******************************************************************/
#define XPAR_INTC_SINGLE_BASEADDR 0xD0020200
#define XPAR_INTC_SINGLE_HIGHADDR 0xD002021F
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_OPB_INTC_0_DEVICE_ID
#define XPAR_RS232_UART_0_IP2INTC_IRPT_MASK 0X000001
#define XPAR_OPB_INTC_0_RS232_UART_0_IP2INTC_IRPT_INTR 0
#define XPAR_LEDS_8BIT_IP2INTC_IRPT_MASK 0X000002
#define XPAR_OPB_INTC_0_LEDS_8BIT_IP2INTC_IRPT_INTR 1
#define XPAR_SYSACE_COMPACTFLASH_SYSACE_IRQ_MASK 0X000004
#define XPAR_OPB_INTC_0_SYSACE_COMPACTFLASH_SYSACE_IRQ_INTR 2
#define XPAR_SYSTEM_PHY_MII_INT_N_MASK 0X000008
#define XPAR_OPB_INTC_0_SYSTEM_PHY_MII_INT_N_INTR 3
#define XPAR_LL_TEMAC_0_TEMACINTC0_IRPT_MASK 0X000010
#define XPAR_OPB_INTC_0_LL_TEMAC_0_TEMACINTC0_IRPT_INTR 4
#define XPAR_PPC440_VIRTEX5_0_DMA0RXIRQ_MASK 0X000020
#define XPAR_OPB_INTC_0_PPC440_VIRTEX5_0_DMA0RXIRQ_INTR 5
#define XPAR_PPC440_VIRTEX5_0_DMA0TXIRQ_MASK 0X000040
#define XPAR_OPB_INTC_0_PPC440_VIRTEX5_0_DMA0TXIRQ_INTR 6

/* canonical names */
#define XPAR_LLTEMAC_0_TEMACINTC0_IRPT_MASK XPAR_LL_TEMAC_0_TEMACINTC0_IRPT_MASK
#define XPAR_INTC_0_LLTEMAC_0_VEC_ID XPAR_OPB_INTC_0_LL_TEMAC_0_TEMACINTC0_IRPT_INTR
/******************************************************************/

/******************************************************************/

#define XPAR_XSYSACE_MEM_WIDTH 16
/* Definitions for driver SYSACE */
#define XPAR_XSYSACE_NUM_INSTANCES 1

/* Definitions for peripheral SYSACE_COMPACTFLASH */
#define XPAR_SYSACE_COMPACTFLASH_BASEADDR 0xD0030100
#define XPAR_SYSACE_COMPACTFLASH_HIGHADDR 0xD003017F
#define XPAR_SYSACE_COMPACTFLASH_DEVICE_ID 0
#define XPAR_SYSACE_COMPACTFLASH_MEM_WIDTH 16

/******************************************************************/

#define XPAR_CPU_PPC440_CORE_CLOCK_FREQ_HZ 400000000
#define XPAR_CPU_PPC440_IDCR_BASEADDR 0x00000000
#define XPAR_XLLDMA_USE_DCR
//#define CONFIG_XILINX_LLDMA_USE_DCR

/******************************************************************/

/******************************************************************/

/* U-Boot Redefines */

/******************************************************************/

#define XPAR_UARTNS550_0_BASEADDR (XPAR_RS232_UART_0_BASEADDR+0x1000)
#define XPAR_UARTNS550_0_HIGHADDR XPAR_RS232_UART_0_HIGHADDR
#define XPAR_UARTNS550_0_CLOCK_FREQ_HZ XPAR_XUARTNS550_CLOCK_HZ
#define XPAR_UARTNS550_0_DEVICE_ID XPAR_RS232_UART_0_DEVICE_ID

/******************************************************************/

#define XPAR_EMAC_0_BASEADDR XPAR_ETHERNET_MAC_BASEADDR
#define XPAR_EMAC_0_HIGHADDR XPAR_ETHERNET_MAC_HIGHADDR
#define XPAR_EMAC_0_DMA_PRESENT XPAR_ETHERNET_MAC_DMA_PRESENT
#define XPAR_EMAC_0_MII_EXIST XPAR_ETHERNET_MAC_MII_EXIST
#define XPAR_EMAC_0_ERR_COUNT_EXIST XPAR_ETHERNET_MAC_ERR_COUNT_EXIST
#define XPAR_EMAC_0_DEVICE_ID XPAR_ETHERNET_MAC_DEVICE_ID

/******************************************************************/

#define XPAR_SYSACE_0_BASEADDR XPAR_SYSACE_COMPACTFLASH_BASEADDR
#define XPAR_SYSACE_0_HIGHADDR XPAR_SYSACE_COMPACTFLASH_HIGHADDR
#define XPAR_SYSACE_0_MEM_WIDTH XPAR_SYSACE_COMPACTFLASH_MEM_WIDTH
#define XPAR_SYSACE_0_DEVICE_ID XPAR_SYSACE_COMPACTFLASH_DEVICE_ID

/******************************************************************/

#define XPAR_IIC_0_BASEADDR XPAR_IIC_BUS_BASEADDR
#define XPAR_IIC_0_HIGHADDR XPAR_IIC_BUS_HIGHADDR
#define XPAR_IIC_0_TEN_BIT_ADR XPAR_IIC_BUS_TEN_BIT_ADR
#define XPAR_IIC_0_DEVICE_ID XPAR_IIC_BUS_DEVICE_ID

/******************************************************************/

#define XPAR_CORE_CLOCK_FREQ_HZ XPAR_CPU_PPC440_CORE_CLOCK_FREQ_HZ

/******************************************************************/
